-- +goose Up
CREATE TABLE users (
	id UUID PRIMARY KEY,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE feeds (
	id UUID PRIMARY KEY,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	name TEXT UNIQUE NOT NULL,
	url TEXT UNIQUE NOT NULL,
	user_id UUID NOT NULL
		REFERENCES users(id)
		ON DELETE CASCADE
);

CREATE TABLE feed_follows (
	id UUID PRIMARY KEY,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	feed_id UUID NOT NULL REFERENCES feeds(id)
	ON DELETE CASCADE,
	user_id UUID NOT NULL REFERENCES users(id)
	ON DELETE CASCADE,
	UNIQUE (feed_id, user_id)
);

-- +goose Down
DROP TABLE IF EXISTS feed_follows;
DROP TABLE IF EXISTS feeds;
DROP TABLE IF EXISTS users;
